{% set name = "bw2data" %}
{% set version = "4.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ae45536c6abedeb385586c7b4646c4620e3cdeb747f3e97250bbc86e6d741ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - blinker
    - bw_processing >=0.9.5
    - bw2parameters
    - deepdiff >=7.0.1,<7.1
    - deprecated
    - fsspec
    - lxml
    - numpy <2
    - peewee >=3.9.4
    - pint
    - platformdirs
    - pydantic-settings
    - python >={{ python_min }}
    - rapidfuzz
    - scipy
    - snowflake-id >=1.0.2,<1.1
    - stats_arrays
    - structlog
    - tqdm
    - typing_extensions
    - voluptuous
    - wrapt

test:
  imports:
    - bw2data
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/brightway-lca/brightway2-data
  summary: Tools for the management of inventory databases and impact assessment methods. Part of the Brightway2 LCA Framework.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/brightway-lca/brightway2-data

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
