{% set name = "bw2data" %}
{% set version = "4.0.dev29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd019e5fdb6d20a5de43e5a852a7d215694eb106df2d83aa165c85a09be37362

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - bw2-uptodate = bw2data.bin.bw2_uptodate:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - scipy
    - numpy
    - peewee >=3.9.4
    - lxml
    - platformdirs
    - tqdm
    - voluptuous
    - whoosh
    - wrapt
    - bw2parameters
    - bw_processing
    - stats_arrays

test:
  imports:
    - bw2data
  requires:
    - pip
  commands:
    - pip check
    # No test of bw2-uptodate as no --help or --version available

about:
  home: https://github.com/brightway-lca/brightway2-data
  summary: Tools for the management of inventory databases and impact assessment methods. Part of the Brightway2 LCA Framework.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/brightway-lca/brightway2-data

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
